spring:
  datasource:
    url: jdbc:mysql://a3-databaseprimaryinstance-kx6oehoi4cmh.cwolf6iufkvy.us-east-1.rds.amazonaws.com:3306/ass2?serverTimezone=UTC&amp&useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
