

spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: sample@gmail.com
      password: 12345678
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
    kafka:
        bootstrap-servers: 44.214.213.141:9092
        consumer:
          group-id: my-group

