spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ass1?serverTimezone=UTC&amp&useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
#  port: 3080
  port: 3000
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

